<?php

namespace ContactBoxBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * mailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mailRepository extends EntityRepository
{
}
